version: "3"

vars:
  APP_NAME: "bc"
  VERSION: "1.0.0"
  LDFLAGS: "-X 'cmd/cli/main.go.version={{.VERSION}}'"

tasks:
  build-darwin:
    cmds:
      - CGO_ENABLED=0 GOOS=darwin go build -ldflags {{.LDFLAGS}} -a -installsuffix cgo -o bin/darwin/{{.APP_NAME}} ./cmd/cli/main.go

  build-amd64:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags {{.LDFLAGS}} -a -installsuffix cgo -o bin/amd64/{{.APP_NAME}}-darwin ./cmd/cli/main.go

  build-arm:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags {{.LDFLAGS}} -a -installsuffix cgo -o bin/arm/{{.APP_NAME}}-darwin ./cmd/cli/main.go

  build-arm64:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags {{.LDFLAGS}} -a -installsuffix cgo -o bin/arm64/{{.APP_NAME}}-darwin ./cmd/cli/main.go

  build-windows:
    cmds:
      - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags {{.LDFLAGS}} -a -installsuffix cgo -o bin/windows/{{.APP_NAME}}.exe ./cmd/cli/main.go

  gorelease:
    cmds:
      - goreleaser release --clean
      - rm -rf dist
