#!/usr/bin/env zsh

set -o errexit
set -o pipefail

# Globals
COMMIT_MSG_LEN=20

error(){
    echo "ERROR: $*" >&2
}

info(){
    echo "INFO: $*" >&2
}

usage(){
    cat <<EOF
BetterCommit (bc) is a small utility which will help you make an habit of writing better commit messages.

Usage: ${0##*/} <subcommands>

Available commands:
    add         Adds all the changes to staging area
    commit      Adds and commits all the changes
    branch      Creates a new branch

Example usage:

    ${0##*/} add

EOF
}


function commit(){
    local operation=$1
    local ticket=$2
    local commitmessage=$3
    git add .
    git commit -m "$operation($ticket): $commitmessage"
}

function prepare_commit(){
	read "TICKET?Is this commit related to any projects tickets / Components / features (eg: JIRA-124, button, vpc): "
	read "OPERATION?Enter which git operation did you performed (eg: add, update, del): "
    info "Files modified"
    git status --porcelain
    read "COMMITMSG?What did you $OPERATION: "
    case "$OPERATION" in
        add | update | del )
            messagelength=${#COMMITMSG}
            if [[ "$messagelength" -le $COMMIT_MSG_LEN ]]; then
                echo "COMMIT MESSAGE TOO SHORT. COMMIT MESSAGE SHOULD BE AT LEAST $COMMIT_MSG_LEN CHARS LONG."
            fi
            ;;
        *)
            read -q "REPLY?Operation \"$OPERATION\" not understood."
            exit 1
            ;;
    esac
    commit "$OPERATION" "$TICKET" "$COMMITMSG"

}

function has_git(){
    if [ ! -d ".git" ]; then info "This is not a git repo. I am not needed here. Ta Ta !!!"; exit 1; fi
}


function branch(){
    local branch_name
    local sanitized_branch_name
	read "TICKET?Is this commit related to any projects tickets / Components / features (eg: JIRA-124, button, vpc): "
	read "OPERATION?What kind of work is this (eg: bugfix, feat, demo, test): "
    read "WORK?What work will be done in this branch: "
    branch_name="$OPERATION/$TICKET/$WORK"
    # Sanitize branch name by removing all the spaces with dash "-"
    sanitized_branch_name=${branch_name// /-}
    git checkout -b "$sanitized_branch_name"
}

function main(){
    local commandName=$1; shift
    case "$commandName" in
        commit)
            has_git
            prepare_commit
            ;;
        branch)
            branch
            ;;
        help)
            usage
            exit 1
            ;;
        *)
            error "Could not understand the command. Try running \"bc help\"."
            exit 1
            ;;
    esac
}

if [ "$#" != 1 ]; then
    info "Not enough argument provided."
    echo ""
    usage
    exit 1
fi

main "$@"